### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by mandoof1** [samogod/tornado#7]
i changed the torrc file and enabled control panel and that seemed to fix a part of the issue the other part it refuses to connect i checked and tor is on heres the output

[INF] Tornado Engine (v1.3.5) is initialising.
[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[16-01-2023 14:46:28] [INF] ControlPort is setting at /etc/tor/torrc file..
sudo: service: command not found
[16-01-2023 14:46:28] [SUCCESS] ControlPort is ready.
[16-01-2023 14:46:28] [INF] Tor connection is starting..
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/stem-1.8.1-py3.10.egg/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tornado", line 33, in <module>
    sys.exit(load_entry_point('tornado==1.3.5', 'console_scripts', 'tornado')())
  File "/usr/lib/python3.10/site-packages/tornado-1.3.5-py3.10.egg/tornado/__main__.py", line 142, in main
  File "/usr/lib/python3.10/site-packages/tornado-1.3.5-py3.10.egg/tornado/__main__.py", line 122, in process
  File "/usr/lib/python3.10/site-packages/tornado-1.3.5-py3.10.egg/tornado/__main__.py", line 68, in connection
  File "/usr/lib/python3.10/site-packages/stem-1.8.1-py3.10.egg/stem/control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/lib/python3.10/site-packages/stem-1.8.1-py3.10.egg/stem/socket.py", line 503, in __init__
    self.connect()
  File "/usr/lib/python3.10/site-packages/stem-1.8.1-py3.10.egg/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/usr/lib/python3.10/site-packages/stem-1.8.1-py3.10.egg/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused

**Comment by mandoof1** [comment]
i tried changing this 
with Controller.from_port(port=9051) as controller:
to this
with Controller.from_port(address='127.0.0.1', port=9051, control_port=9051, control_socket='/var/run/tor/control') as controller:
no luck still

**Comment by samogod** [comment]
The issue has been fixed with the new commit.
